### ISSUE TITLE
Create waitlist for tool_types

### ISSUE THREAD

**Issue by pkoenig10** [sc0v/binder-app#101]
#100 needs to be done first.

**Comment by minigeek** [comment]
I feel like this should be on tool_types rather than specific tools.

**Comment by arakla** [comment]
Perhaps we need overarching types, such as ladders, saws, cleaning items,
etc... And sub types/item groups such as 8ft ladders, brooms, magnetic
sweeps, etc...

**Comment by minigeek** [comment]
But what do we really need that many types for? Aren't they still usually
going to search? What problem would we be trying to solve?

**Comment by arakla** [comment]
If we have the wait list on type of tool, are we just having categories for
specific things like 8ft ladders, 12ft ladders, etc...? Or would it make
sense to have a type and sub type (I'm just making up potential edge
cases). Not saying we should go one way or another, just something to
consider.

**Comment by pkoenig10** [comment]
@minigeek should've clarified I meant tool_types. @arakla I don't think we need subtypes.

**Comment by pkoenig10** [comment]
Things to consider:
- Notify when checking out tool when waitlist is not empty
- Notify when checking in a tool with a waitlist
- Do we want a central place to view all waitlists? (Probably not)

**Comment by pkoenig10** [comment]
Waitlist for each tool type will be listed on each page for the tool of that type.
