### ISSUE TITLE
Improve top level navigation

### ISSUE THREAD

**Issue by pkoenig10** [sc0v/binder-app#105]
We should somehow move most of the quick links into the navbar menu so they can be accessed anywhere.  Currently the navigation can be confusing.

Maybe think about if we need all the sections we currently have (Tasks, Milestones, etc.).

**Comment by kunalsin** [comment]
Same thing here - if you could provide some more details on how you want this to look like - I can finish this off

**Comment by arakla** [comment]
Unless Patrick had something in mind, I think this will involve doing some
user testing to see what would be best for different user types.

**Comment by pkoenig10** [comment]
This is something we should discuss in a meeting before we begin working on it.
