### ISSUE TITLE
Finish implementing Tasks page

### ISSUE THREAD

**Issue by pkoenig10** [sc0v/binder-app#106]
This is mostly done.  We just need to
1. Add a link to the top-level navigation
2. Finish implementing the Tasks sidebar (partially done)

**Comment by kunalsin** [comment]
What exactly do you want to see for this issue? I can tackle it as it looks like its almost done

**Comment by pkoenig10** [comment]
Currently the tasks page can viewed at /tasks.  Here a list of things Aamer and I came up with.

1. Add a tasks link to the top-level nav under "Other links"
2. Add a button to complete tasks on the tasks page, near the edit and delete buttons
3. Add a column to the tasks sidebar with a button to complete tasks (similar to the image below).

![image](https://cloud.githubusercontent.com/assets/5273164/13163606/8488e3c0-d67c-11e5-9b6f-7ad67f1bd774.png)

**Comment by pkoenig10** [comment]
Also make sure to checkout the code with f3a0cb2.  I made a small change to the sidebar behavior.

**Comment by kunalsin** [comment]
For the link in the top-level nav, can everyone have access to the link and see all the tasks on the page??

**Comment by pkoenig10** [comment]
Only SCC members should be able to access the tasks page.

**Comment by kunalsin** [comment]
When an scc member clicks on the complete button:
1) The completed flag should be set to true
2) Should the task still be displayed in the tasks list or should only the uncompleted tasks be displayed

**Comment by arakla** [comment]
If there is a way to view completed tasks, then I think that it is not
absolutely necessary to keep showing them. If there is no way to view the
completed tasks, then I would not want them to disappear.

**Comment by pkoenig10** [comment]
It would be nice to have a drop down to view all, completed, or uncompleted tasks.  Identical to the all, checked in, checked out drop down for tools.

**Comment by kunalsin** [comment]
Got it
