### ISSUE TITLE
Allow admins to manually modify downtime

### ISSUE THREAD

**Issue by pkoenig10** [sc0v/binder-app#109]

**Comment by pkoenig10** [comment]
I'd like to expose the list of taken downtime periods to each organization's page.  This shouldn't be too difficult as all the information is stored as ```organization_timeline_entries```.

**Comment by pkoenig10** [comment]
The view already exists for this information.  The index view for organization_timeline_entries shows all the downtime entries (just not currently in routes.rb).

This task should also clean up the MVC for organization_timeline_entries.  Currently downtime is treated "specially" (as compared to structural and electrical entries) in the fact that the index views default to showing downtime.  We should change this so downtime is separate, as are the structural and electrical entries.

**Comment by purelogiq** [comment]
Quick question about downtime: do orgs have 4hr downtime for the entire duration of Carnival/building or just like each day?

Can you describe downtime again? Is it during the building phase or the actual Carnival phase?

**Comment by minigeek** [comment]
Orgs get 4 hours total during operations (while Midway is open to the
public). They have to let the trailer know before they start taking
downtime and when they stop.

**Comment by arakla** [comment]
Also, downtime shouldn't continue once Midway closes, but should resume
when Midway opens if the Booth still isn't staffed.



Aamer F. Rakla
B.H.A. Information Systems & Drama: Production and Stage Management
Carnegie Mellon University, 2016

Boss Ambassador (Mentor), Student Life Office
Financial Advisor, Student Dormitory Council
Treasurer, Spring Carnival Committee

**Comment by purelogiq** [comment]
Does the app know when "Midway Closes" is? Or we will have to add that feature. If so I will open a new issue for that.

**Comment by purelogiq** [comment]
Also @RONNCC the change in pull request #113 might have already fixed the downtime index page not working. Sorry for combining it into that PR.

**Comment by pkoenig10** [comment]
The app doesn't know the hours, but I'd rather it not because they change every year and it would be one more thing to update.  Being able to manually edit them should be sufficient.

**Comment by RONNCC** [comment]
be able to add downtime entries on the downtime page

**Comment by RONNCC** [comment]
downtime remaining : 4 hours - if you click 4 hours it then goes to their page

**Comment by RONNCC** [comment]
looks like status history page / tasks page with edit/delete/new
