### ISSUE TITLE
Bar underneath Rapid Tool Checkin to show checkouts doesnt do anything

### ISSUE THREAD

**Issue by RONNCC** [sc0v/binder-app#112]
Image: http://i.imgur.com/rc1QbYk.png

Doesnt seem to actually show checked out tools or anything - is it just there cosmetically?

**Comment by RONNCC** [comment]
You can see this change at https://is67373-binder-app-ronncc.c9users.io/ also

**Comment by RONNCC** [comment]
Specifically looks like 
![image](https://cloud.githubusercontent.com/assets/1313566/13033174/cae635fc-d2da-11e5-943a-ff023ea89008.png)

**Comment by arakla** [comment]
I get the feeling it looks like this because the side bar items use the
same partial, I think.

Having a list of tools that are checked out, excluding org & SCC hardhats,
would be helpful, but will get too long for the sidebar.

**Comment by RONNCC** [comment]
I don't think any used that one? But please tell me if I caused unexpected behavior :-)

Also yup I was going to put a scrollbar on it

**Comment by arakla** [comment]
I think it'll be fine and we would need to look at it and see how we feel.
That being said, why do we need to select an org to check-in a tool?
Otherwise I think this looks pretty good.

One thing to potentially consider/discuss is combing the rapid tool
checkout/check-in.

**Comment by pkoenig10** [comment]
Can you explain what the original issue was? That bar was there as a horizontal divider for the table that would be shown as tools are scanned.

I don't think we need a scroll bar; as Aamer said, this list doesn't get very long.  And when we have a lot of items (mostly hardhats) its helpful to have that visual feedback of the list growing longer to ensure the item was actually scanned in.

I like the idea of combining multiple check-in/check-outs, possible have the same sidebar panel but just two separate buttons for each action.

**Comment by arakla** [comment]
Although, what might work better than two buttons after scanning would be
selecting checkout or check-in and then scanning the tool(s).

**Comment by pkoenig10** [comment]
Agreed.  Two reasons I like this better are

1) We can provide better verification that the scanned tools are able to be checked in/out (because this logic is opposite for checkins vs checkouts).
2) This will declutter the sidebar, which is a currently is slight usability mess.

**Comment by RONNCC** [comment]
sorry - my bad, i'll revert this!

**Comment by RONNCC** [comment]
>> todo: make a checkin/checkout radio button at the top of rapid tool stuff
