### ISSUE TITLE
Add comments field for documents

### ISSUE THREAD

**Issue by pkoenig10** [sc0v/binder-app#120]
This should be similar to descriptions for other models.  This is necessary so we can use the Documents framework for plan submission/review in future years.  Booth chairs will upload plans and booth committee will add comments.

**Comment by RONNCC** [comment]
now you can edit/add comments - where should this show though? i.e. should it be a new column in the documents tracker/org tab? It seems like that could get very unwieldy if there are many comments

**Comment by pkoenig10** [comment]
Agreed. I was thinking that the comments would only be displayed in the show view for each document.

**Comment by purelogiq** [comment]
Are these comments like "1 official comment" or a thread of comments like this issue page (doesn't have to be nested)?

**Comment by pkoenig10** [comment]
The intention is that it will be used as a place for both chairs to give feedback on both plans. So just a paragraph of text is fine.

**Comment by purelogiq** [comment]
So right now of course booth chairs can't upload documents but in the future it is assumed they would be able to upload docs without being able to write in the comment field. Correct? Ronnie's current pull request is good if that's the case.

**Comment by purelogiq** [comment]
Here's how it looks.
![doccomms](https://cloud.githubusercontent.com/assets/7828780/13276887/c799a53c-da91-11e5-80b7-fc7d062d29b4.PNG)

**Comment by pkoenig10** [comment]
So who has permission to write in the comments field? Just SCC members?

**Comment by purelogiq** [comment]
Well right now only people who can make documents. Which is SCC members and admins. Even on the master branch I don't think booth chairs can create documents.

**Comment by pkoenig10** [comment]
After thinking about this for a little, I think it might be best if we drop this feature.  Originally my intention was to use this framework for reviewing booth plans.  However giving booth chairs permissions to upload document could lead to two issues.

1) They will likely abuse the privilege and upload garbage documents because they find it entertaining.
2) There will likely be instances where booth chairs forget to tag a document with their organization.  We could certainly force this association by looking at their user info but this seems to complicate things more than are needed.

The documents feature is still valuable to store the final version of plans so booth committee can use them as a reference during Build Week.  But I think using Binder as a way to review plans might not be the best idea.  I should have thought this through more before opening this issue.

On a broader note, I think the general rule of thumb should be that only SCC members have create, update, or delete permissions.  Giving booth chairs permission beyond reading information seems to be an invitation for abuse.  Just something to think about in other issues and in future discussions.

Let me know what you think.

**Comment by RONNCC** [comment]
Ah - should we close this ticket then?
