### ISSUE TITLE
Hakiri is showing security issues because of out of date dependencies

### ISSUE THREAD

**Issue by minigeek** [sc0v/binder-app#121]
[https://hakiri.io/github/sc0v/binder-app/master](https://hakiri.io/github/sc0v/binder-app/master)

Most if not all of these are due to out-of-date dependencies, someone should update versions and make sure everything still works.

**Comment by pkoenig10** [comment]
Yeah I noticed this at the beginning of the year.  I'll have the student team work on that for this semester.

**Comment by purelogiq** [comment]
This is one of my interests so I'll grab this. Hopefully updating gems won't break anything. (I'll make sure to do some regression testing)

**Comment by pkoenig10** [comment]
Let's just update Ruby + Rails + gems to the latest versions.  Some of the issues look like they are only resolved in beta versions of Rails 5.0, but I'd rather just stick to the latest stable releases.

This will also clear up all the dependency warnings in Gemnasium.

**Comment by purelogiq** [comment]
Yea from the looks of it updating Rails to the latest 4x version, and Devise will take care of most of them. I will also double check the one with routes having :controller in them.
Doubt that I can do better than that, but, well see.

**Comment by purelogiq** [comment]
nvm

**Comment by minigeek** [comment]
Sorry I sniped this, I was bored and trying to re-setup my dev box (absolutely loving Cloud 9 btw) and figured this would be a good first task, also assumed you were asleep by the time I started coding last night so I didn't want to buy you and ask.

**Comment by purelogiq** [comment]
No problem. I hadn't started this yet and we've been pushing it off till the end of the project anyways.
