### ISSUE TITLE
Anyone can add memberships for other users

### ISSUE THREAD

**Issue by pkoenig10** [sc0v/binder-app#135]
Only SCC members should be able to change memberships.  Users should also be able to change their own memberships.

**Comment by minigeek** [comment]
Should users be able to add memberships or just remove? Also this creates
the potential for badness if someone deletes all their memberships for
things like tool checkouts and fines. In the past we didn't want anyone but
SCC to be able to edit any memberships. The general idea was that they
really don't change, so as long as they're entered correctly the first time
they shouldn't need to edit, and if they really need to they can stop by
the trailer and ask the coordinator to change it for them.

**Comment by pkoenig10** [comment]
Makes sense.  SCC can edit all memberships.  Booth chairs can edit memberships for their org (to make people booth chairs).
