### ISSUE TITLE
Improve Shibboleth login workflow

### ISSUE THREAD

**Issue by pkoenig10** [sc0v/binder-app#136]
Two issues:

1) Right now the page immediately redirects to the CMU Shibboleth login page.  This shouldn't happen until the user selects login.
2) After logging in with Shibboleth, the user is not logged in until they click the log in button (at which time they are immediately authenticated because they are already logged in with Shibboleth).

**Comment by purelogiq** [comment]
This may have to do with the Apache configuration, i.e. which path is being authenticate (root /, /login, etc.)

**Comment by pkoenig10** [comment]
I think that might be partly to blame.  I'm going to investigate it in my free time.  Its not a super critical issue.

**Comment by minigeek** [comment]
We had done this originally I belive so that the whole site would be private to CMU only. Was probably overzealous then, probably overzealous now.

**Comment by pkoenig10** [comment]
I just had to change the path protected by Shibboleth in the Apache config. This path is detailed in the omniauth-shibboleth documentation.
