### ISSUE TITLE
Make Event Log

### ISSUE THREAD

**Issue by pkoenig10** [sc0v/binder-app#146]
Log of events (phone calls, emergencies, etc.) that occur on Midway.  Should be similar to organization_status_entry with types of events and notes for each one.

The log entries should also have a some sort of acknowledgement boolean similar to "is_completed" in tasks or "is_approved" charges. Only admins should be able to mark an entry as acknowledged.

The types should also have a display field (like organization_status_types). Any unacknowledged log entries with a type that has display set to true should be shown in in the sidebar like the tasks do now.  This is to make the current coordinator aware of any pending notes.

These should be searchable from the search box.

**Comment by RONNCC** [comment]
things that coordinators dont care about like phone calls - like you don't need to know a phone call happen, admins can go to event_login - things like important notes, make sure they dont help themselves need to show up in the list

**Comment by RONNCC** [comment]
if the type is displayable, sdc members can approve it. if not then only admins

**Comment by arakla** [comment]
Just a typo correction, SCC members, not SDC members

**Comment by RONNCC** [comment]
> make it look like charges
> yellow bars if unacknowledged
> have an unacknowledged button 
> only admins get acknowledge 
> acknowledge button in the sidebar - only things in sidebar are displayable
