### ISSUE TITLE
Add text alerts for tool waitlist

### ISSUE THREAD

**Issue by pkoenig10** [sc0v/binder-app#150]
Texts can be sent using carrier email domains.  Texts should be sent when a tool is checked in for which the waitlist is not empty.  Texts should be sent to booth chairs and the individual on the waitlist.

**Comment by minigeek** [comment]
I've also integrated Twillio, although you have to pay per-text.

**Comment by pkoenig10** [comment]
I have noticed that,  The payment my only reservation, especially when this allows us to do it for free.

**Comment by arakla** [comment]
That being said, it looks like it would only be $7.50 or so for 1000
messages, so the cost for would probably negligible if it is easier/more
reliable to use Twilio over the Rails email and the Andrew mail relay. Let
me know if we need to setup an account as we will need to get contracts
approval (this usually only take a few hours, but can take 24-48hrs).
ᐧ



Aamer F. Rakla
B.H.A. Information Systems & Drama: Production and Stage Management
Carnegie Mellon University, 2016

Boss Ambassador (Mentor), Student Life Office
Financial Advisor, Student Dormitory Council
Treasurer, Spring Carnival Committee

**Comment by arakla** [comment]
Depending on what we go with, we could look at removing someone from the
waitlist by texting back "Cancel", but that might be outside the scope for
the available time frame.
ᐧ



Aamer F. Rakla
B.H.A. Information Systems & Drama: Production and Stage Management
Carnegie Mellon University, 2016

Boss Ambassador (Mentor), Student Life Office
Financial Advisor, Student Dormitory Council
Treasurer, Spring Carnival Committee

**Comment by purelogiq** [comment]
Do you want the text to be sent to just the first person on the waitlist, or the first 3 people,  or everyone?

**Comment by pkoenig10** [comment]
I might put this on hold for this year, until we see how well the waitlist works. Even with making the coordinator aware when checking out waitlisted tools, I can see us sending a text, accidentally checking out the tool, and the org getting upset. This is mostly because we don't really have a way to enforce how long we will hold a toll for someone.

**Comment by purelogiq** [comment]
Ok, lets see how the waitlist works this Carnival and during the remaining semester we can develop a plan for future Carnivals.

**Comment by pkoenig10** [comment]
Or we could tell booth chairs that they will get a text immediately but we make no guarantees about holding tools. I think this is the better solution because it moves the burden or responsibility from us to the booth orgs. Also it would mean we don't have to worry about the wait list when checking out tools.

**Comment by arakla** [comment]
We could also add a field for how long an org has been on a waitlist and if
it is older than X time, we remove them.

Because, if we don't alert orgs in some way, will they just be checking
back in occasionally until it is available, but it could get checked out.
I'm all for making a future plan, but I just don't see orgs checking in
occasionally.



Aamer F. Rakla
B.H.A. Information Systems & Drama: Production and Stage Management
Carnegie Mellon University, 2016

Boss Ambassador (Mentor), Student Life Office
Financial Advisor, Student Dormitory Council
Treasurer, Spring Carnival Committee

**Comment by arakla** [comment]
Or that what Patrick said. Sorry I'm responding by email and I guess I get
delayed notifications.



Aamer F. Rakla
B.H.A. Information Systems & Drama: Production and Stage Management
Carnegie Mellon University, 2016

Boss Ambassador (Mentor), Student Life Office
Financial Advisor, Student Dormitory Council
Treasurer, Spring Carnival Committee

**Comment by pkoenig10** [comment]
True, if we're going to use he wait list we probably need this. @purelogiq focus on the checkout stuff now and we will discuss on Friday after I've looked into various ways to send SMSs.

**Comment by purelogiq** [comment]
Text the first person on the waitlist when a tool is checked in, after 15 minutes text the next person if the exact tool checked in is still there. (note add the tool number in the text message).

After 12 hours remove the person that got the text from the waitlist. Do not refresh if a new tool is checked in.

Note text all the booth chairs and person signed up on the waitlist.

**Comment by purelogiq** [comment]
@pkoenig10 Actually a gmail account for Binder to mail from would be great. It will also allow people to reply (though I won't be doing automated scanning, an SCC member can always look at it).

**Comment by purelogiq** [comment]
When you make the account you will need to enable IMAP in the account settings. Also as a personal reminder we will have to figure out how to store the password outside of the github repo while still being able to set it as an environment variable in production.

**Comment by arakla** [comment]
Just curious, is there any reason not to use the CMU mail relay?

**Comment by pkoenig10** [comment]
And just curious, why can't we just use Rails built-in Action Mailers. Replying is something we don't really need because I highly doubt people will reply.

**Comment by purelogiq** [comment]
Well it will use Rails built-in Action Mailers regardless. I just wanted to inform you of the option to [configure it to go through gmail](http://guides.rubyonrails.org/action_mailer_basics.html#action-mailer-configuration-for-gmail) if you guys wanted replys (e.g. for watch shift texts). If not then we can also just use no-gmail (i think).

**Comment by pkoenig10** [comment]
Let's just stick without Gmail for now (we can configure the from address and name to be whatever we want anyways) and do that later if we want to.  It seems like it would be a trivially thing to switch.

**Comment by sclark** [comment]
This is also now a part of #244, so I will close this issue too.
