### ISSUE TITLE
Tool cart

### ISSUE THREAD

**Issue by pkoenig10** [sc0v/binder-app#151]

**Comment by purelogiq** [comment]
The tool cart is going to be the replacement for the outdated checkout feature. It will be implemented as a sidebar box that combines both the "Rapid tool checkin" and the "Multiple tool checkout" feature.

The sidebox will have a box to list the tools you want to "add", the list of tools to be checked in or checked out, and 2 buttons: 1 to checkout the listed tools and 1 to checkin the tools.

I will be refactoring the checkouts controller to use mainly json responses and the front end will be using ajax to get that info.
