### ISSUE TITLE
Adding duplicate items to the store cart creates another entry

### ISSUE THREAD

**Issue by pkoenig10** [sc0v/binder-app#163]

**Comment by AkshayGoradia** [comment]
Fixed so that if an item is already in the cart, adding the same item again increments the quantity of that item in the cart, rather than creating a new entry.

**Comment by pkoenig10** [comment]
Which PR fixed this?

**Comment by blinblinblin** [comment]
@pkoenig10 I believe it's this: https://github.com/sc0v/binder-app/pull/237. As you said, we clustered it in a bunch of commits. In our next group meeting, we will address your point of making separate branches for each PR that we work on so that this does not happen again.

**Comment by pkoenig10** [comment]
@blinblinblin Thanks!
