### ISSUE TITLE
Allow fractional store prices

### ISSUE THREAD

**Issue by pkoenig10** [sc0v/binder-app#168]
Currently the store only allows integer prices.

**Comment by sclark** [comment]
After running the db migration the fractional-store-prices branch builds in the CI.

**Comment by sclark** [comment]
This should allow for fractional store prices, so I will close this issue.

I will submit a pull request for this and all the other new features after our IS team merges bug fixes into master.

**Comment by pkoenig10** [comment]
@slclark you're fine to close this issue, just make sure to test this (any all new features) out in staging.

**Comment by sclark** [comment]
@pkoenig10 for sure. Will do.
