### ISSUE TITLE
Any SCC Member can create new event types

### ISSUE THREAD

**Issue by arakla** [sc0v/binder-app#179]
Any SCC member can create new event types, this should be admin only, correct?
Also any SCC member can view all events in the event log, I think this is supposed to be admin only as well. SCC members should only be able to see displayable notes.

**Comment by pkoenig10** [comment]
No everyone can see all events in the event log. There's nonreason for only admins to see some events. Also SCC members should be able to create new types in case something comes up that warrants a new type. Please talk to me before submitting issues that are just questions to avoid cluttering the issues page.
