### ISSUE TITLE
Event Log - Ok & Un-ok does not work

### ISSUE THREAD

**Issue by arakla** [sc0v/binder-app#199]

**Comment by pkoenig10** [comment]
Details? What happens?

**Comment by arakla** [comment]
404 Not Found ... the exact error displayed is the Page Not Found Error

"The page you were looking for doesn't exist.

You may have mistyped the address or the page may have moved."

**Comment by arakla** [comment]
Apparently for notes made after a certain point, or maybe it is just me, pressing ok doesn't work either. Or maybe it is for event types that weren't seeded? Or maybe non-displayable events. I'm not sure and can't check right now.

**Comment by pkoenig10** [comment]
The answer is that events are very broken.  I'm sure most things are pretty trivial fixes. I will probably go through and harden Binder a little bit this summer. I'll fix those issues then.

**Comment by eleanorwilson** [comment]
Bug fixed for event okay/un-okay, refer to pull request #234
