### ISSUE TITLE
Updating/edit a charge appears to lose the issued to user

### ISSUE THREAD

**Issue by arakla** [sc0v/binder-app#202]
Binder doesn't actually lose the issued to name, it just appears to because it does not display it on the edit page as it is just a text field. So this is more of a design issue and understanding/documenting how Binder works.

A quick fix would be to just have note on edit page saying that binder hasn't lost it.

**Comment by blinblinblin** [comment]
I'm closing this issue since we established using placeholder value as a temporary solution works.
