### ISSUE TITLE
Charge Summary for each org

### ISSUE THREAD

**Issue by arakla** [sc0v/binder-app#209]
Like the charge overview page, but for booth chairs to see a summary of each charge type
Additionally, they should be able to view a filtered version of their charges of a specific charge type.

**Comment by pkoenig10** [comment]
I added a "Charges" button to the org page that will take you to a view showing only their charges.  So this issue has become a duplicate of #178.

**Comment by arakla** [comment]
Does the Charges button provide totals for each charge type?

**Comment by pkoenig10** [comment]
No, but that is part of #210. That task can also include updating those org-specific charge index pages to have more useful information, if needed.

There is alot of (relatively easy) work that can be done to improve the charges workflow.  I think your issues make it pretty clear where the workflow suffers the most and is sufficient feedback to improve the current solution.
