### ISSUE TITLE
Advisor & Financial Admin Users

### ISSUE THREAD

**Issue by arakla** [sc0v/binder-app#216]
With Binder becoming more relied on, Advisors (such as Greek Advisors/HFs) and Financial Admins (such as Student Life) need to be able to login and see the charges as well as verify the amounts being charged to the orgs they are responsible for.

So, we need new a new user type/role for these users.

**Comment by pkoenig10** [comment]
There is already a Student Activities/DOSA org. We can just make sure they have the appropriate permissions.

**Comment by arakla** [comment]
See my comment in #215
