### ISSUE TITLE
Shift Test - CI Fail

### ISSUE THREAD

**Issue by eleanorwilson** [sc0v/binder-app#235]
Need to fix shift test, so that it doesn't fail the CI test. Works locally but consistently off by the same time when running it through CI
<img width="926" alt="screen shot 2017-03-04 at 5 14 17 pm" src="https://cloud.githubusercontent.com/assets/18669359/23582708/10f25966-00fe-11e7-8b44-ad545cc12f97.png">

**Comment by sclark** [comment]
Is there still a branch where this test is failing on the CI server?

**Comment by blinblinblin** [comment]
I don't think so since we commented out the test. If you want to reproduce the error, you can always go to the unit test class for shift and re-comment the last test function.

**Comment by pkoenig10** [comment]
@blinblinblin can you guys fix the test before merging into master? Commenting out tests because they break the CI sort of defeats the purpose of having tests

**Comment by eleanorwilson** [comment]
@pkoenig10 Yeah we will. We commented/opened a issue to remind ourselves because it's a very small error with server times but runs fine locally. We wanted to focus in on our scope and return to it after notification feature has been created.

**Comment by sclark** [comment]
This test now passes on the CI server, so I am closing the issue.
