### ISSUE TITLE
Text notification on addition to queue

### ISSUE THREAD

**Issue by agotsis** [sc0v/binder-app#255]
In line with #244 , I think there are applications for notifications on queue actions.

For me, I'd love to receive a text when someone is added to the electrical queue. As an extension, perhaps I could reply to clear an org from the queue, but I definitely care a whole lot more about receiving texts when Orgs are added to the Electrical queue.

Seems like there is already an infrastructure for this, but could be as simple as an email to #####@carrier.com.

**Comment by sclark** [comment]
@agotsis Resolved by #271 ?

**Comment by agotsis** [comment]
Agreed.

**Comment by sclark** [comment]
Then I'll close this when #271 gets merged.
