### ISSUE TITLE
Update FAQs in the Seed

### ISSUE THREAD

**Issue by minigeek** [sc0v/binder-app#64]
https://github.com/sc0v/binder-app/blob/master/db/seeds.rb#L208

I already updated them to the best of my knowledge and replaced names, but I don't actually know if all the answers are the same this year.

**Comment by csweintraub** [comment]
The answers are all of the same. I will get you info about rides ASAP as Swank's went out of business 1 month ago so we are waiting to get bids back. I should be able to get you that info in a few weeks as we aim to decide on a vendor this week.

In terms of the names, the seed file is still showing Emily, Jackson and Rachel's names. Have you just not pushed your changes?

**Comment by minigeek** [comment]
Yeah, I need all your SCC members including yourself for admins, hadn't
gotten that far and that is easy to do later. I just meant FAQs which
should be all good now and shifts and such that I need to script and import.

**Comment by csweintraub** [comment]
They're all good.

**Comment by minigeek** [comment]
Ok, thanks!
