### ISSUE TITLE
Update Tasks in the Seed

### ISSUE THREAD

**Issue by minigeek** [sc0v/binder-app#65]
https://github.com/sc0v/binder-app/blob/master/db/seeds.rb#L356

I updated the one-time tasks (which need to be updated based on the schedule) but we need to update the recurring ones as well with new info (and I suggest my new format to make it easier next year).

**Comment by csweintraub** [comment]
We want the same recurring tasks as last year. Do you just mean to re-do the dates?

**Comment by minigeek** [comment]
Yep, you can use the format I used for the "one time tasks" of day (defined
above) + hours. It will show up some number of hours beforehand.

**Comment by csweintraub** [comment]
Pushed. 

Just a heads up that I was re-reading the FAQ and I didn't catch that fireworks will either be Thursday or Saturday this year depending on whether or not the city gives us clearance to hold fireworks over Midway. I will be getting that result tomorrow and will let you know.

Also, as of today, the awards ceremony is starting at 4:30. I can make both changes to the FAQ once I get for sure confirmation.
