### ISSUE TITLE
Potential DoS when searching for a single character

### ISSUE THREAD

**Issue by nharper** [sc0v/binder-app#66]
On the home page, when searching with a single character term (e.g. "a"), the server takes a long time to respond (I crashed binder.springcarnival.org earlier today with this query). On a dev instance on my desktop, the search did respond after about 10 seconds; the time appeared to be spent mostly doing ldap searches and updating the cache columns in the participants table. The ldap searches and sql updates were being done sequentially (i.e. one ldap search and one sql update for each andrewid, instead of batching them).

The sequential searches and cache updates appear to be caused by the call to participant.formatted_name in [search.html.erb](https://github.com/sc0v/binder-app/blob/b794f131ee93e7f09fd2493c5cb56be492932161/app/views/home/search.html.erb#L23), which ends up calling update_cache for each Participant. Potential fixes could be to update the cache in Participant.search, or to pre-warm the cache (being careful to not have lots of cache entries expiring during a critical time during carnival).

**Comment by minigeek** [comment]
This is just because we are scripting people into the db. This is cached in the db directly so this cost is a one-time issue. If you refresh the page a second time it should load instantly.
