### ISSUE TITLE
What search functionality should work when logged out?

### ISSUE THREAD

**Issue by nharper** [sc0v/binder-app#69]
By searching for something like "a" (and then iterating through all vowels), one can pretty easily get a list of all participants, tool checkouts, organizations, etc. Should this information be visible to a logged-out user (or other logged-in users)?

**Comment by minigeek** [comment]
This is a bug, we pretty much totally locked the site when you're logged out. Most of the links don't work and should be removed when logged-out, haven't gotten around to it.
