### ISSUE TITLE
Required Youtube Video doesn't work at all on mobile which means you can't sign on mobile.

### ISSUE THREAD

**Issue by minigeek** [sc0v/binder-app#71]
This seems like SUPER silly. What exactly is the goal of this beyond everyone hating us? We have no requirements to do this level of "training" and no one's going to watch anyway, it will just make it impossible to move people through the line as we have 100 people milling about ignoring their phone (assuming we can actually get it to work on mobile. Thoughts @csweintraub

**Comment by merichar** [comment]
This version is for before they're standing on line, but I don't make the requirements, I just implement them. Also, works on mobile for me. What are you seeing in iOS?

**Comment by minigeek** [comment]
Just a black box

**Comment by minigeek** [comment]
And why is there a second version? Is the video important or no? If you can sign it without watching the video but there is a video that somepeople were required to watch then you're literally asking to get sued. This should be taken to LCA if you are messing with the waiver (which you effectively are by making people sign that they watched the movie).

**Comment by merichar** [comment]
Score one for FF on android. 

I'm not a legal expert, but it seems there are issues if you're willing to sign that you watched a movie after not having watched the movie.

Version that committee will use to have people sign waivers (instead of people self-signing) doesn't have the video embedded because the video will be looping in Wean Commons.

**Comment by minigeek** [comment]
Then we're directly modifying the waiver and should get it approved by LCA.
My point was that we're either modifying it and should get approval, or
we're not and shouldn't do it. As is we should get approval (imho).

**Comment by merichar** [comment]
I'm just the code monkey; you'll have to wait for Carrie to get the real answer, but I assume she and Tim did run whatever changes they made past some reasonable entity.

**Comment by csweintraub** [comment]
Tim and I chatted about this, he approved it and aid we didn't need to get Legal involved. I asked him specifically about that. EH&S has signed off on it and all appropriate stakeholders have watched and reviewed it. 

In terms of the video working on mobile, if that is what we are talking about on this issue, its minor. It doesn't matter and worse comes to worse, we can ask all chairs to not let their orgs sign it on their phones.

**Comment by arakla** [comment]
This should be revisited along with #173 as the move to CFA has gotten more people concerned about this

**Comment by pkoenig10** [comment]
Isn't actually required though? Do we have some agreement where we explicitly stated it is a required video? It doesn't adhere to any official safely requirement, it's just a video we made. Orgs still have to go to trainings.

**Comment by arakla** [comment]
Actually it is as of this year. We actually don't meet all of risks
requirements as they think everyone must watch the video and that it has
been updated with fire safety requirements, what to do if there is a fire,
and fire evacuation information.
ᐧ



Aamer F. Rakla
B.H.A. Information Systems & Drama: Production and Stage Management
Carnegie Mellon University, 2016

Boss Ambassador (Mentor), Student Life Office
Financial Advisor, Student Dormitory Council
Treasurer, Spring Carnival Committee

**Comment by minigeek** [comment]
I agree with Patrick, I don't think we should really try to "require" the
video and should instead just show it by default and I bet 90% of people
won't skip. If it doesn't work on mobile then just applink at the end and
hope they watch it.

**Comment by arakla** [comment]
It is no longer us requiring it tough, unless we talk to Andrew and he
corrects me, from what I understand Risk Management and Insurance are
requiring this video of we are on CFA lot.

On Friday, May 6, 2016, Chase Brownell <notifications@github.com> wrote:

> I agree with Patrick, I don't think we should really try to "require" the
> video and should instead just show it by default and I bet 90% of people
> won't skip. If it doesn't work on mobile then just applink at the end and
> hope they watch it.
>
> On Thu, May 5, 2016 at 9:50 PM Aamer Rakla <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
> > Actually it is as of this year. We actually don't meet all of risks
> > requirements as they think everyone must watch the video and that it has
> > been updated with fire safety requirements, what to do if there is a
> fire,
> > and fire evacuation information.
> > ᐧ
> >
> >
> >
> > Aamer F. Rakla
> > B.H.A. Information Systems & Drama: Production and Stage Management
> > Carnegie Mellon University, 2016
> >
> > Boss Ambassador (Mentor), Student Life Office
> > Financial Advisor, Student Dormitory Council
> > Treasurer, Spring Carnival Committee
> >
> > On Fri, May 6, 2016 at 12:47 AM, Patrick Koenig <
> notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> > wrote:
> >
> > > Isn't actually required though? Do we have some agreement where we
> > > explicitly stated it is a required video? It doesn't adhere to any
> > official
> > > safely requirement, it's just a video we made. Orgs still have to go to
> > > trainings.
> > >
> > > —
> > > You are receiving this because you commented.
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/sc0v/binder-app/issues/71#issuecomment-217347645>
> > >
> >
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly or view it on GitHub
> > <https://github.com/sc0v/binder-app/issues/71#issuecomment-217347889>
> >
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/sc0v/binder-app/issues/71#issuecomment-217372865>
>


-- 


Aamer F. Rakla
B.H.A. Information Systems & Drama: Production and Stage Management
Carnegie Mellon University, 2016

Boss Ambassador (Mentor), Student Life Office
Financial Advisor, Student Dormitory Council
Treasurer, Spring Carnival Committee
