### ISSUE TITLE
List of Builders, Booth Chairs and SCC Members

### ISSUE THREAD

**Issue by csweintraub** [sc0v/binder-app#78]
Page to spit out CSV of these three lists for CMU alert system. I just need the category of the list and all of the andrew ids associated with the category.

**Comment by pkoenig10** [comment]
This can be done using the Rails dbconsole.

**Comment by minigeek** [comment]
I think the idea is that there is a number of these kinds of things that we could script and then just throw together onto a "tools" page accessible only by admins to make these things easier and more repeatable year to year (and so fewer things require the console).

**Comment by minigeek** [comment]
You're welcome to leave it closed, I'm just trying to provide history as I see you commenting. You own this so ultimately any decisions are up to you, I'm just here to help you out.

**Comment by pkoenig10** [comment]
Yeah I'm just getting things organized before the student team takes over this week.  Mostly thinking about what features we want and what features might be outside the scope of Binder.

**Comment by pkoenig10** [comment]
Included in #102
