### ISSUE TITLE
Checkout multiple tools

### ISSUE THREAD

**Issue by merichar** [sc0v/binder-app#80]
Shopping cart style?

**Comment by pkoenig10** [comment]
Binder supports checking in multiple tools with the Rapid Tool Check-In sidebar.  We should make something similar for checking out tools.

**Comment by pkoenig10** [comment]
Put in sidebar alongside Rapid Tool Checkin.

**Comment by RONNCC** [comment]
What would this look like? Should it be barcode too?

**Comment by arakla** [comment]
This would be a side bar item that first takes an ID card or Andrew ID. You
would then verify the participant and need to select the org you are
checking the tools out for. Then scan all the barcodes. If a tool is
checked out, it should be checked in and then out to the new person/org.

Ideally, this should be able to be done for the sidebar or a tool checkout
page. Like, if I scan a tool, choose checkout, then I want to checkout
another tool to the same person/org, there should be an option for that.

**Comment by arakla** [comment]
This is another thing where you would need to look at the workflow and see
what makes the most sense because currently the workflow is not intuitive.

**Comment by pkoenig10** [comment]
Here's what I was thinking.  We combine the rapid check-in/check-out side panel.  We add an additional "Check-Out" button next to the current "Check-In" button.  So the workflow would be the following.

1) The user scans a bunch of tools in the sidebar
2) The user selects "Check-Out"
3) the user is directed to the same page as in the current tool checkout workflow, to enter a users name and organization.  The only difference is that it applies this checkout to multiple tools.

I also agree that it would nice to have a button somewhere to add another tool during the checkout process, but I think we should focus on the above workflow first.

**Comment by pkoenig10** [comment]
See comment here: https://github.com/sc0v/binder-app/issues/112#issuecomment-183957939

**Comment by purelogiq** [comment]
Super quick question, can anyone shed some light on [this](https://github.com/sc0v/binder-app/blob/master/app/controllers/checkouts_controller.rb#L50) part of the code. It seems like there is some provision to dynamically create a hardhat when checking it out by using a barcode < 0 or > 2500. Should this feature remain in my re-factored checkout process?

**Comment by minigeek** [comment]
Yes, although it should just be an autofill, not auto create (give user an
opportunity to cancel). When we barcode hard hats we often don't enter them
as tools and later need to check them out quickly.

There is some chance that they're now all created (assuming we have a
snapshot of last year's database), but I think as long as we provide a
cancel button this makes the coordinator's life easier.

**Comment by purelogiq** [comment]
Thanks, also is there a reason that the json format is supported in that controller? I don't see any where besides the rapid tool checkin that ajax queries are being used.

**Comment by purelogiq** [comment]
Also @pkoenig10 or @arakla can you comment on whether these hardhats are now all created and if this is how it should work this year?

**Comment by pkoenig10** [comment]
I've updated the seeds file with all the hard hats from the production database from last year.  All of the hard hats should be in the database when we check them out for distribution.  On the off chance that we're missing a couple we can manually add them.  I think that is certainly worth it for cleaning up this kinda weird code.

Furthermore, there are a ton of tools with barcodes > 2500 that are not hard hats.  I think its a little dangerous to make the assumption that anytime we are doing mass checkout its for hard hats.

**Comment by purelogiq** [comment]
Got it. Fixing...

**Comment by arakla** [comment]
I think this was made under the assumption with better tool tracking we
wouldn't pass that number anytime soon, but that was a few years ago.

Also there will definitely be new tools, there are always things that come
up every year, including hardhats because new ones are put together during
distribution when needed.

If anything, I could be remembering wrong, but at one point there was a
bulk hardhat checkout and a barcode scanned at that point should be created
as a new hardhat. Then again that may have been a spreadsheet and it was
just bulk check-in.

**Comment by pkoenig10** [comment]
I think it was a spreadsheet. I know last year we used a spreadsheet and then put them into Binder later. But I'd rather not do that this year if we can help it.

**Comment by arakla** [comment]
Agreed. I think the biggest issue with moving it to binder was that by
default binder requires an Andrew ID on checkout. But I'm not sure if that
was that reason bulk checkout to an org doesn't exist.
