### ISSUE TITLE
Checkout Tool as Replacement

### ISSUE THREAD

**Issue by merichar** [sc0v/binder-app#81]
Like for batteries. Just for an org to do a trade.

**Comment by pkoenig10** [comment]
Implement as a side bar, similar to the Rapid Tool Check-In sidebar.

**Comment by pkoenig10** [comment]
Put in sidebar alongside Rapid Tool Checkin.

**Comment by purelogiq** [comment]
This will be implemented as a sidebar widget with 1 field to enter scanned tools. Then after scanning the first tool it will populate the 'Checked In' tool field and after scanning the next one it will populate the  'Check out' tool field. When clicking 'Swap' it will check in the old tool and checkout the new tool using the org and participant from the checked in tool.

**Comment by pkoenig10** [comment]
Just to clarify, the tool scanning shouldn't have to be in a specific order. Binder should know which tool is to be checked-in and which is to be checked-out and fill the appropriate field.
