### ISSUE TITLE
List booth chair phone number with shifts

### ISSUE THREAD

**Issue by merichar** [sc0v/binder-app#83]
So it's easy to find when the shift doesn't show

**Comment by pkoenig10** [comment]
It takes one click to get to the organization page and see the phone numbers.

**Comment by arakla** [comment]
That being said, when you have a lot going on, or a coordinator who is new, sometimes a small thing like this is helpful. That being said, if binder could auto-notify the chairs, that would be great.

**Comment by pkoenig10** [comment]
There's a separate issue for that, #84.
