### ISSUE TITLE
Put BIRs online

### ISSUE THREAD

**Issue by merichar** [sc0v/binder-app#86]
Otherwise order more pads.

**Comment by pkoenig10** [comment]
Organizations already have a status field.  Basically extend this status field to support a history of statuses/reports.

**Comment by arakla** [comment]
I believe there should already be a way to view the status history of an
org, we just need to be able to add different statuses and use the notes
more I think.



Aamer F. Rakla
B.H.A. Information Systems & Drama: Production and Stage Management
Carnegie Mellon University, 2016

Boss Ambassador (Mentor), Student Life Office
Financial Advisor, Student Dormitory Council
Treasurer, Spring Carnival Committee

**Comment by minigeek** [comment]
This was a somewhat separate thing when BIR's were more granular, if they
aren't giving BIR's for individual screws (it actually happened many times
at one point) then you're totally right the status field is good enough.
There's actually already status history from the org's page if that
satisfies your requirements.

**Comment by pkoenig10** [comment]
Cool.  Then I'll just add more types to suit our needs.

**Comment by arakla** [comment]
That being said, maybe we should look at having it improved, so it's an actual workflow/order so that certain steps/statuses can't happen without others being done. It would also make sense to integrate this with plan reviews, in my opinion.

We should also have it only display the current academic year and be able to view previous years separately.

**Comment by pkoenig10** [comment]
I don't think Binder needs to be something that maintains info across years.  Its isn't necessary for how its used and it wasn't really designed with that in mind.

But I agree that we could improve and integrate statuses more.  I've opened at new issue #98.
