### ISSUE TITLE
Add Documents tab to organization page

### ISSUE THREAD

**Issue by pkoenig10** [sc0v/binder-app#90]
Binder already supports uploading documents and associating them with an organization.  We should be able to view those documents from the organizaiton pages.

**Comment by RONNCC** [comment]
change: remove the edit/delete/upload tab from the organization page

**Comment by pkoenig10** [comment]
@RONNCC you didn't remove the upload tab from the organization page in #144.  Please make another pull request to address that.  In the future, please let me merge the pull requests so I can at least glance over them first, even for minor things like this.

**Comment by RONNCC** [comment]
@pkoenig10  I apologize - I didn't merge the PR, I was just closing the issue as there were no more comments on it

**Comment by pkoenig10** [comment]
Sorry! Just realized I was the one that merged that.  So that's on me.  I'll push a fix.

**Comment by pkoenig10** [comment]
I was completely mistaken, this was fine.  Not sure what I was seeing earlier but probably just a side effect of jumping between branches too much.
