### ISSUE TITLE
Participants can't view public documents

### ISSUE THREAD

**Issue by pkoenig10** [sc0v/binder-app#93]

**Comment by RONNCC** [comment]
Changed behavior so that participants can see all documents that are public or are assigned to an organization that they belong to.

Previous behavior was that a doc had to be public and either the organization was blank or they belonged to it

**Comment by RONNCC** [comment]
Also fixed it so that it create the upload folder if it doesnt exist rather than erroring

**Comment by RONNCC** [comment]
How to see the change:
1.go to https://is67373-binder-app-ronncc.c9users.io
2.signin as admin
3.upload a document to public documents
4. signout
5. signin as participant
6. look at documents
7. should be able to see your doc there

**Comment by RONNCC** [comment]
Fix looks like 
![image](https://cloud.githubusercontent.com/assets/1313566/13033181/11851e56-d2db-11e5-8cfc-6e3c253a4db3.png)

**Comment by pkoenig10** [comment]
I ran into some error pages when trying to upload or update a document.  The errors occurred when checking for or creating the upload directory.

**Comment by RONNCC** [comment]
why would you have an empty organization for a document @pkoenig10 ?

**Comment by minigeek** [comment]
We had empty organizations for truly public documents such as terms and
conditions. We also don't want to expose non-public docs to participants
ever, this was created for things such as fines which we wouldn't want to
expose to an entire org, versus public things such as designs which we
might want to expose to a whole org, but not to all people in all orgs.

**Comment by RONNCC** [comment]
hmm i think this behavior was different from what is now expected? 

e.g. "We also don't want to expose non-public docs to participants ever" is different? Please correct me if i'm wrong @pkoenig10  :)

**Comment by minigeek** [comment]
You guys are welcome to change this logic, I was just trying to provide
context for existing behavior.

Additionally, by participant I meant "participants who aren't booth chairs"
shouldn't be able to see non-public docs.

**Comment by RONNCC** [comment]
thank you :) sorry i meant to clarify if the old or the new behavior was to be preferred

**Comment by pkoenig10** [comment]
Okay, sorry @RONNCC, I should have looked into this more thoroughly.  So it appears that originally the permissions were as follows:

Empty + Public = Everyone
Empty + Private = Admin
Org + Public = All participants in Org
Org + Private = Booth Chairs of Org

I have two minor concerns with this logic:
1) The designations are not entirely clear.  Especially if booth chairs are uploading documents, I doubt they will understand that org + public still means that only their org can see it.
2) SCC members should have access to all documents.  Specifically I'm thinking of booth committee who needs to review plans.

The only benefit of the original logic is that is allowed for an access distinction between booth chairs and their org.  But I can't really see this as something that is strongly desired/needed.

I think we should leave the updated logic.  The empty organization makes sense for documents that are to be public and not attributed to an organization, like the terms and conditions.  So the new permissions model is as follows:

Empty + Public = Everyone
Empty + Private = SCC Members
Org + Public = Everyone
Org + Private = All participants in Org + SCC Members

The distinction between (Empty + Public) and (Org + Public) is simply that we can tag documents with an organization.

**Comment by RONNCC** [comment]
updated #114  should have these permissions :)
