### ISSUE TITLE
Who's On Midway page

### ISSUE THREAD

**Issue by pkoenig10** [sc0v/binder-app#99]
Create a Who's On Midway page where SCC members (maybe just booth committee) check in when they arrive to Midway.  Booth chairs can then easily check if someone is available.  Basically a replacement for the whiteboard in the trailer.

**Comment by minigeek** [comment]
I agree this is a good idea, I would just hesitate to over-engineer
something which currently works really well already. In general if you're
looking for someone on booth committee your best bet is to just radio
asking for someone from booth committee. This has two advantages, namely
the HoB knows what all's going on if they pay attention to their radio, and
it lets people get into stuff knowing that if somebody needs something
there are other people on radio who can potentially help. Moving this info
to the website removes those benefits without really adding new ones. It's
also then much harder for booth chairs to come into the trailer quickly and
see who's around as I doubt you would want to expose this info to them via
the site (and I wouldn't recommend it as it removes the trailer as the
center of knowledge).

**Comment by pkoenig10** [comment]
Using Binder is probably worse than using the whiteboard for the reasons above.  It also requires that SCC members check in/out when they arrive/leave the trailer, which is a hassle.
